services:
  viably-proxy:
    build: .
    container_name: viably-proxy
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:8085:8085"
    networks:
      - viably-network

networks:
  viably-network:
    external: true
