"""Add OAuth accounts table

Revision ID: 3187ef12ef3f
Revises: u1v2w3x4y5z6
Create Date: 2026-03-09 21:09:29.196009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3187ef12ef3f'
down_revision: Union[str, Sequence[str], None] = 'u1v2w3x4y5z6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_requests', sa.Integer(), nullable=True),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
    sa.Column('rate_limit_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_tokens', sa.Integer(), nullable=True),
    sa.Column('rate_limit_remaining_tokens', sa.Integer(), nullable=True),
    sa.Column('rate_limit_tokens_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requests_today', sa.Integer(), nullable=False),
    sa.Column('requests_total', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_name'), 'oauth_accounts', ['name'], unique=False)
    op.drop_index(op.f('idx_artifacts_created_at'), table_name='artifacts')
    op.create_index('idx_artifacts_created_at', 'artifacts', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_conversations_created_at'), table_name='conversations')
    op.create_index('idx_conversations_created_at', 'conversations', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.alter_column('credit_transactions', 'token_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_credit_transactions_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_user_created'), table_name='credit_transactions')
    op.create_index(op.f('ix_credit_transactions_transaction_type'), 'credit_transactions', ['transaction_type'], unique=False)
    op.alter_column('deployments', 'platform_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('deployments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deployments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('deployments_custom_domain_idx'), table_name='deployments', postgresql_where='(custom_domain IS NOT NULL)')
    op.alter_column('email_logs', 'subject',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('email_logs', 'error_message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('email_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_email_logs_status_created'), table_name='email_logs', postgresql_where="((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('FAILED'::character varying)::text]))")
    op.drop_index(op.f('idx_email_logs_type_status'), table_name='email_logs')
    op.drop_index(op.f('idx_email_logs_user_created'), table_name='email_logs')
    op.drop_index(op.f('idx_email_logs_user_id'), table_name='email_logs')
    op.create_index(op.f('ix_email_logs_created_at'), 'email_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_logs_email_type'), 'email_logs', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_logs_status'), 'email_logs', ['status'], unique=False)
    op.create_index(op.f('ix_email_logs_user_id'), 'email_logs', ['user_id'], unique=False)
    op.drop_column('email_logs', 'resend_message_id')
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'yookassa'::character varying"))
    op.alter_column('payments', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_payments_crypto_payment_id'), table_name='payments')
    op.drop_column('payments', 'crypto_payment_id')
    op.alter_column('projects', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'generated_code',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('templates', 'config_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('templates', 'code_template',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'code_template',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('templates', 'config_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('projects', 'generated_code',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('projects', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('payments', sa.Column('crypto_payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_payments_crypto_payment_id'), 'payments', ['crypto_payment_id'], unique=False)
    op.alter_column('payments', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'yookassa'::character varying"))
    op.add_column('email_logs', sa.Column('resend_message_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_email_logs_user_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_status'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_email_type'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_created_at'), table_name='email_logs')
    op.create_index(op.f('idx_email_logs_user_id'), 'email_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_email_logs_user_created'), 'email_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_email_logs_type_status'), 'email_logs', ['email_type', 'status'], unique=False)
    op.create_index(op.f('idx_email_logs_status_created'), 'email_logs', ['status', 'created_at'], unique=False, postgresql_where="((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('FAILED'::character varying)::text]))")
    op.alter_column('email_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_logs', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('email_logs', 'subject',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.create_index(op.f('deployments_custom_domain_idx'), 'deployments', ['custom_domain'], unique=True, postgresql_where='(custom_domain IS NOT NULL)')
    op.alter_column('deployments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deployments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deployments', 'platform_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_credit_transactions_transaction_type'), table_name='credit_transactions')
    op.create_index(op.f('ix_credit_transactions_user_created'), 'credit_transactions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_credit_transactions_type'), 'credit_transactions', ['transaction_type'], unique=False)
    op.alter_column('credit_transactions', 'token_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_conversations_created_at', table_name='conversations', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_conversations_created_at'), 'conversations', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_artifacts_created_at', table_name='artifacts', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_artifacts_created_at'), 'artifacts', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_oauth_accounts_name'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
