"""API service category prompt."""

API_CATEGORY_PROMPT = """## API Services (Python / FastAPI)

### Architecture
- FastAPI 0.109+ with async endpoints
- Pydantic v2 models for request/response validation
- Repository pattern for data access
- Dependency injection for services

### Project Structure
- main.py — FastAPI app with CORS, error handlers
- routes/ — API router modules
- models/ — Pydantic schemas
- services/ — business logic
- requirements.txt — pinned dependencies

### Security
- Input validation via Pydantic
- CORS configuration
- Environment variables for secrets (python-dotenv)
- Error responses without internal details

### Best Practices
- Type hints on all functions
- Async/await for I/O operations
- Structured logging
- Health check endpoint (/health)
- OpenAPI documentation (auto-generated by FastAPI)
"""
